### ISSUE TITLE
May be, mistake in models.py

### ISSUE THREAD

**Issue by tol2000** [lastorel/pytion#33]
Hello! Thank you for the interesting notion api object wrapper.
As I understood, class PropertyValue does not fully support images now?
But I tried to use this class in database pages  and got items of Property class (I expected PropertyValue class)
Here is my code:
```
res = db.db_filter(property_name="Owner", value="John", property_type="select", condition='equals')
for p in res.obj:
    print(f'url: {p.url}')
    for field_name, field_property in p.properties.items():
        print(f'    {field_name}, type: {type(field_property)}')
```
May be, I misunderstood something, but, may be in the string 541 of models.py (fragment below) you have to wrote `name: (PropertyValue(data)` instead of `name: (Property(data)`?
```
self.properties = {
            name: (Property(data) if not isinstance(data, PropertyValue) else data)
            for name, data in kwargs["properties"].items()
        }
```

**Comment by lastorel** [comment]
for v1.3.1 #32 will be fixed

**Comment by tol2000** [comment]
I didn't dig deep into the deeps of Notion API jsons, I learned your library, it was enough for my tasks. Objects - its cool! )
So, it was not your bug, just temp feature) Ok, I will follow your and Notion progress:), hope that will be number one Notion API object wrapper!

_P.S. Приятно, что разработчик русскоязычный :) Реально из живых существующих питоновских либов по notion твой, похоже, самый крутой! Буду следить.
